language: java
jdk:
  - oraclejdk8
  - oraclejdk9
matrix:
  include:
    - jdk: openjdk10
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
notifications:
  email:
    - ansell.peter@gmail.com
after_success:
  - mvn clean test jacoco:report coveralls:report
