#!/bin/bash
# This script runs the CSV Summariser retrieval code.
# Before running this script for the first time 
# you may need to run:
#     chmod +x csvsum
#

if [ ! -d "target/appassembler/bin" ]; then
    mvn -quiet clean install -DskipTests -Djetty.skip
fi

chmod u+x target/appassembler/bin/*
target/appassembler/bin/csvsum "$@"
